trigger:
        - main

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

        steps:
        - task: Docker@2
          displayName: Build the demo image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
